const library={
    en: {
        categories:'Categories ',
        ViewAll:'View All',
        NewArrival:'New Arrival',
        search:'Search',
        dashbord:'Dashbord',
        WishList:'Wish List',
        myBasket:'My Basket',
        AddToBasket:'Add To Basket',
        ItemTotal:'Item Total',
        Delivery:'Delivery',
        TaxesandCharges:'Taxes and Charges',
        PlaceOrder:'Place Order',
        OrderSummary:'Order Summary',
        DeliveryAddress:'Delivery Address',
        Email:'Email',
        DeliveryTime:'Delivery Time',
        MobileNumber:'Mobile Number',
        TotalPrice:'Total Price',
        OrderSuccessfullyPlaced:'Order Successfully  Placed',
        Yourinvoicenumberis:'Your invoice number is',
        Wellprocessyourorderassoonaspossible:'We’ll process your order as soon as possible.',
        ContinueShopping:'Continue Shopping',
        ConfirmOrder:'Confirm Order',
        Profile:'Profile',
        Home:'Home',
        AllCategories:'All Categories',
        WishList:'Wish List',
        YourOrders:'Your Orders',
        ManageProfile:'Manage Profile',
        PrivacyPolicy:'Privacy Policy',
        Tearmsofuse:'Tearms of use',
        FAQs:'FAQs',
        ChangeLanguage:'Change Language',
        LogOut:'Log out',
        EditYourProfile:'Edit Your Profile',
        ShippingAddress:'Shipping Address',
        PaymentMethods:'Payment Methods',
        OrderHistory:'Order History',
        DeliveryStatus:'Delivery Status',
        Favorite:'Favorite',
        ChangePassword:'Change Password',
        Help:'Help',
        RateApp:'Rate App',
        ShareApp:'Share App',
        EditProfile:'Edit Profile',
        SaveDetails:'Save Details',
        MyOrder:'My Order',
        PastOrder:'Past Order',
        Ongoning:'Ongoning' ,
        OrderDetailes:'Order Detailes' ,
        MyOrders:'My Orders',
        OrderID:'Order ID',
        Address:'Address',
        CurrentlyUnavailable:'Currently Unavailable ',
        OutOfStock:'out of stock',
        PhoneNumber:'Phone Number',
        Time:'Time' ,
        TrackingStatus:'Tracking Status',
        OrderPlaced:'Order Placed ',
        OrderPrepared:'      Order Prepared ',
        OrderDispatch:'     Order Dispatch ',
        outForDeliver:'     Out For Deliver ',
        OrderRecived:'     Order Recived ',
        OrderDate:'Order Date',
        ProductPage:'Product Page',
        GoToBasket:'Go To Basket',
        Description:'Description',
        RelatedItems:'Related Items',
        AllProducts:'All Products',
        Notifications:'Notifications',
        Name:'Name ',
        Note:'NOTE: Please wait fo the access else you can call on +91 xxxx xxxx',
        AllCategories:'All Categories',
        BillDetailes:'Bill Details',
        total:'Total',
        Quantity:'Qty.',
        Language:'Language',
        ChooseYourPrefferedLanguage:'Choose Your Preferred Language',
        NoInternetConnection:'No Internet Connection',
        PleaseTryAgainLater:'Please Try Again Later',
        AreYouSureYouWant:"Are You Sure You Want ",
        cancel:"Cancel",
        Logout:"Logout",
        signup:"Sign Up",
        signin:"Sign In",
        Email:"Email",
        password:"Password",
        gallery:"Gallery",
        confirmpassword:"Confirm Password",
        forgotpassword:"Forgot Password?",
        forgotPassword:"Forgot Password",
        pleaseenterpassword:"Please Enter Password",
        shopdetails:"Shop Detailes",
        donthaveaccount:"Don't Have Account?",
        signUP:"Sign Up",
        selectyourfile:"Select Your File",
        shopname:"Shop Name",
        nameofuser:"Name Of User",
        addressofshop:"Address Of Shop",
        phonenumber:"Phone",
        camera:"Camera",
        imageofshop:"Image Of Shop",
        adharcard:"Adhar Card",
        businesscard:"Business card",
        salesorreference:"Sales/Reference",
        referencecode:"Reference Person Code",
        alreadyhaveaccount:"Already Have Account?",
        signIn:"Sign In",
        weigths:"Weigths",
        selectweigth:"Select Weigth",
        pleasecheckyouremail:"Please Check Your Email",
        confirmemail:"Confirm Email",
        orderhistory:"Order History",
        ongoingorder:"Ongoing Order",
        pastorder:"Past Order",
        pleaseentervaildEmail:"Please Enter Valid Email",
        passworandconfirmpassword:"Password and Confirm Password are not Same",
        pleaseentershopname:"Please Enter Shop Name",
        pleaseenterusername:"Please Enter User Name",
        pleaseenterphonenumber:"Please Enter Phone Number",
        pleaseentervaildphonenumber:"Please Enter Valid  Phone Number",
        pleaseinsertshopimage:"Please Enter Valid Phone Number",
        pleaseentershopaddress:"Please Enter Address of Shop",
        pleaseinsertbuisnesscard:"Please Insert Business Card",
        pleaselectweigthofproduct:"Please Select weigth of Product",
        addtowishlist:"add to wishlist",
        pleaseenteremailtoconfirm:"Please enter your email to receive a confirmation and set new password",
        addedtowishlist:"added to wishlist",
        removedfromwishlist:"removed from wishlist",
        thisproductarenotunavailable:"These products are currently unavailable",
        Productid:"Product Id",
        clearall:"Clear All",
        status:"Delivery status",
        pleaseenterEmail:"Please Enter Email",
        invaildcredentails:"Invaild Credentails",
        pleasecheckyouremailandpassword:"Please check you Email Id and Password",
        okay:"ok",
        weakpassword:"password should be atleast 6 digit",
        emailalreadyexist:"this email already exist",
        congratulations:"Congratulation",
        sucessfullregister:"You have Sucessfully Register",
        requestunderreview:"Your Request is Under Review",
        wrongpassword:"Password not match with email",
        wrongemail:"Email you entered is not right",
        referencecodeerror:"Reference person Code Doesn't Exist",
        invaildemail:"email is not vaild",
        linksend:"link is shared you on given email successfully ",
        alert:"Alert",
        update:"Update",
        updatemsg:"Perfect Digital Mart recommends that you update to the latest version.",
        updatealert:"Update Perffect Digital Mart?",
        nothanks:"No Thanks",
        noproductavailable:'No product available',
        addressavailable:'Your Address Where Product Will be Deliver',
        saveaddress:'Save Address',
        off:"OFF"
      


         },
    gu: {
        categories:'શ્રેણીઓ',
        ViewAll:'બધુજ જુઓ',
        NewArrival:'નવી આગમન',
        search:'શોધ',
        dashbord:'ડેશબોર્ડ',
        WishList:'ઇચ્છા યાદી',
        myBasket:'મારી બાસ્કેટ',
        AddToBasket:'બાસ્કેટમાં ઉમેરો',
        ItemTotal:'આઇટમ કુલ',
        Delivery:'ડિલિવરી',
        TaxesandCharges:'કર અને ચાર્જ',
        PlaceOrder:'ઓર્ડર કરો',
        OrderSummary:'ઓર્ડર સારાંશ',
        DeliveryAddress:'વિતરણ સરનામું',
        Email:'ઇમેઇલ',
        DeliveryTime:'ડિલિવરી સમય',
        MobileNumber:'મોબાઇલ નંબર',
        TotalPrice:'કુલ કિંમત',
        OrderSuccessfullyPlaced:'ઓર્ડર સફળતાપૂર્વક મૂકવામાં આવ્યો',
        Yourinvoicenumberis:'તમારો ભરતિયું નંબર છે',
        Wellprocessyourorderassoonaspossible:'અમે શક્ય તેટલી વહેલી તકે તમારા ઓર્ડર પર પ્રક્રિયા કરીશું.',
        ContinueShopping:'ખરીદારી ચાલુ રાખો',
        ConfirmOrder:'ઓર્ડરની પુષ્ટિ કરો',
        Profile:'પ્રોફાઇલ',
        Home:'ઘર',
        AllCategories:'બધા શ્રેણીઓ',
        WishList:'ઇચ્છા યાદી',
        YourOrders:'તમારો હુકમ',
        ManageProfile:'પ્રોફાઇલ મેનેજ કરો',
        PrivacyPolicy:'ગોપનીયતા નીતિ',
        Tearmsofuse:'વાપરવાના નિયમો',
        FAQs:'પ્રશ્નો',
        OutOfStock:'સ્ટોક પૂરો',
        ChangeLanguage:'ભાષા બદલો',
        LogOut:'લૉગ આઉટ',
        EditYourProfile:' તમારી પ્રોફાઇલ સંપાદિત કરો',
        ShippingAddress:'પહોંચાડવાનું સરનામું',
        PaymentMethods:'ચુકવણીની પદ્ધતિઓ',
        OrderHistory:'ઓર્ડર ઇતિહાસ',
        DeliveryStatus:'ડિલિવરી સ્થિતિ',
        Favorite:'પ્રિય',
        ChangePassword:'પાસવર્ડ બદલો',
        Help:'સહાય કરો',
        CurrentlyUnavailable:'હાલ ઉપલબ્ધ નથી',
        RateApp:'દર એપ્લિકેશન',
        ShareApp:'શેર એપ્લિકેશન',
        EditProfile:'પ્રોફાઇલ સંપાદિત કરો',
        SaveDetails:'વિગતો સાચવો',
        MyOrder:'મારા ઓર્ડર',
        PastOrder:'પાછલો ઓર્ડર',
        Ongoning:'ચાલુ છે' ,
        OrderDetailes:' ઓર્ડર વિગતો   ' ,
        MyOrders:'મારી આદેશ',
        OrderID:'ઓર્ડર આઈડી',
        Address:'સરનામું',
        PhoneNumber:'ફોન નંબર',
        Time:'સમય', 
        TrackingStatus:'ટ્રેકિંગ સ્થિતિ',
        OrderPlaced:'ઓર્ડર મૂક્યો   ',
        OrderPrepared:'ઓર્ડર તૈયાર  ',
        OrderDispatch:'ઓર્ડર રવાનગી',
        outForDeliver:'ડિલિવરી માટે બહાર',
        OrderRecived:'ઓર્ડર મળ્યો',
        OrderDate:'ઓર્ડર તારીખ',
        ProductPage:'ઉત્પાદન પૃષ્ઠ',
        GoToBasket:'ટોકરી પર જાઓ',
        Description:'વર્ણન',
        RelatedItems:'સંબંધિત વસ્તુઓ',
        AllProducts:'બધા ઉત્પાદનો',
        Notifications:'સૂચનાઓ',
        Name:'નામ  ',
        Note:'નોંધ: કૃપા કરીને એક્સેસની પ્રતીક્ષા કરો અન્યથા તમે +91 xxxx xxxx. પર ક करલ કરી શકો છો',
        AllCategories:'બધા શ્રેણીઓ',
        BillDetailes:'બિલ વિગતો',
        total:'કુલ',
        Quantity:'જથ્થો',
        Language:'ભાષા',
        ChooseYourPrefferedLanguage:'તમારી ભાષા પસંદ કરો ',
        NoInternetConnection:'ઇન્ટરનેટ કનેક્શન નથી',
        PleaseTryAgainLater:'પછીથી ફરી પ્રયત્ન કરો',
        AreYouSureYouWant:"શું તમે ખરેખર લોગ આઉટ કરવા માંગો છો?",
        cancel:"રદ કરો",
        selectyourfile:"તમારી ફાઇલ પસંદ કરો",
        Logout:"લૉગ આઉટ",
        signup:"સાઇન અપ",
        signin:"સાઇન ઇન",
        Email:"ઇમેઇલ",
        password:"પાસવર્ડ",
        camera:"કેમેરા",
        gallery:"ગેલેરી",
        confirmpassword:"પાસવર્ડની પુષ્ટિ કરો",
        forgotpassword:"પાસવર્ડ ભૂલી ગયા છો?",
        shopdetails:"દુકાનની વિગતો",
        donthaveaccount:"એકાઉન્ટ નથી?",
        signUP:"સાઇન અપ કરો",
        shopname:"દુકાનનું નામ",
        nameofuser:"વપરાશકર્તાનું નામ",
        addressofshop:"દુકાનનું સરનામું",
        phonenumber:"ફોન નંબર",
        imageofshop:"દુકાનનો ફોટો",
        adharcard:"આધાર કાર્ડ",
        businesscard:"વ્યાપાર કાર્ડ",
        salesorreference:"વેચાણ/સંદર્ભ",
        referencecode:"સંદર્ભ વ્યક્તિ કોડ",
        alreadyhaveaccount:"પહેલેથી જ એકાઉન્ટ છે?",
        signIn:"સાઇન ઇન કરો",
        weigths:"વજન",
        selectweigth:"વજન પસંદ કરો",
        pleasecheckyouremail:"કૃપા કરીને તમારું ઇમેઇલ તપાસો",
        confirmemail:"ઇમેઇલ પુષ્ટિ",
        orderhistory:"ઓર્ડર ઇતિહાસ",
        ongoingorder:"ચાલુ ઓર્ડર",
        pastorder:"ભૂતકાળનો ઓર્ડર",
        pleaseenterpassword:"કૃપા કરીને પાસવર્ડ દાખલ કરો",
        pleaseentervaildEmail:"કૃપા કરીને માન્ય ઇમેઇલ દાખલ કરો",
        passworandconfirmpassword:"પાસવર્ડ અને કન્ફર્મ પાસવર્ડ સરખા નથી",
        pleaseentershopname:"કૃપા કરીને દુકાનનું નામ દાખલ કરો",
        pleaseentershopaddress:"કૃપા કરીને દુકાનનું સરનામું દાખલ કરો",
        pleaseenterusername:"કૃપા કરીને વપરાશકર્તા નામ દાખલ કરો",
        pleaseenterphonenumber:"કૃપા કરીને ફોન નંબર દાખલ કરો",
        pleaseentervaildphonenumber:"કૃપા કરીને માન્ય ફોન નંબર દાખલ કરો",
        pleaseinsertshopimage:"કૃપા કરીને દુકાનની છબીઓ દાખલ કરો",
        pleaseinsertbuisnesscard:"કૃપા કરીને વ્યવસાય કાર્ડ દાખલ કરો",
        pleaselectweigthofproduct:"કૃપા કરીને વજન પસંદ કરો",
        addtowishlist:"ઈચ્છા ની યાદ I માં ઉમેરવું",
        forgotPassword:"ફોરગોટ પાસવર્ડ",
        pleaseenteremailtoconfirm:"કૃપા કરીને પુષ્ટિ મેળવવા માટે તમારો ઇમેઇલ દાખલ કરો અને નવો પાસવર્ડ સેટ કરો",
        addedtowishlist:" વિશલિસ્ટમાં ઉમેર્યું",
        removedfromwishlist:"વિશલિસ્ટમાંથી કાી નાખ્યું",
        thisproductarenotunavailable:"આ ઉત્પાદનો હાલમાં અનુપલબ્ધ છે",
        Productid:"પ્રોડક્ટ આઈડી",
        clearall:"બધું સાફ કરો",
        status:"ડિલિવરીની સ્થિતિ",
        pleaseenterEmail:"કૃપા કરીને ઇમેઇલ દાખલ કરો",
        invaildcredentails:"અનૈતિક પ્રમાણ",
        pleasecheckyouremailandpassword:"કૃપા કરીને તમારું ઇમેઇલ આઈડી અને પાસવર્ડ તપાસો",
        okay:"બરાબર",
        weakpassword:"પાસવર્ડ ઓછામાં ઓછો 6 અંકનો હોવો જોઈએ",
        emailalreadyexist:"આ ઇમેઇલ પહેલેથી અસ્તિત્વમાં છે",
        congratulations:"અભિનંદન",
        sucessfullregister:"તમે સફળતાપૂર્વક નોંધણી કરાવી છે",
        requestunderreview:"તમારી વિનંતી સમીક્ષા હેઠળ છે",
        wrongpassword:"પાસવર્ડ ઇમેઇલ સાથે મેળ ખાતો નથી",
        wrongemail:"તમે દાખલ કરેલો ઇમેઇલ સાચો નથી",
        referencecodeerror:"સંદર્ભ વ્યક્તિ કોડ અસ્તિત્વમાં નથી",
        invaildemail:"ઇમેઇલ માન્ય નથી",
        linksend:"લિંક તમને આપેલ ઇમેઇલ પર મોકલવામાં આવી છે જે સફળતાપૂર્વક પૂર્ણ થઈ છે",
        alert:"એલર્ટ",
        update:"અપડેટ",
        updatemsg:"પરફેક્ટ ડિજિટલ માર્ટ ભલામણ કરે છે કે તમે અપડેટ કરો નવીનતમ સંસ્કરણ.",
        updatealert:"પરફેક્ટ ડિજિટલ માર્ટ અપડેટ કરો?",
        nothanks:"ના આભાર",
        noproductavailable:'કોઈ પ્રોડક્ટ ઉપલબ્ધ નથી',
        addressavailable:'તમારું સરનામું જ્યાં પ્રોડક્ટ પહોંચાડવામાં આવશે',
        saveaddress:'સરનામું સાચવો',
        off:'છૂટ'
        },
    hi:{
        categories:'श्रेणियाँ',
        ViewAll:'सभी को देखें',
        NewArrival:'नया आगमन',
        search:'खोज कर',
        dashbord:'डैशबोर्ड',
        WishList:'इच्छा सूची',
        myBasket:'मेरी टोकरी',
        AddToBasket:'टोकरी में जोड़ें',
        ItemTotal:'आइटम का कुल',
        Delivery:'वितरण',
        TaxesandCharges:'कर और शुल्क',
        PlaceOrder:'आदेश देना',
        OrderSummary:'आदेश सारांश',
        DeliveryAddress:'डिलिवरी का पता',
        Email:'ईमेल',
        DeliveryTime:'डिलीवरी का समय',
        MobileNumber:'मोबाइल नंबर',
        TotalPrice:'कुल कीमत',
        OrderSuccessfullyPlaced:'आदेश सफलतापूर्वक दिया गया',
        Yourinvoicenumberis:'आपका चालान नंबर',
        Wellprocessyourorderassoonaspossible:'हम आपके आदेश को जल्द से जल्द संसाधित करेंगे.',
        ContinueShopping:'खरीदारी जारी रखें',
        ConfirmOrder:'आदेश की पुष्टि',
        Profile:'प्रोफ़ाइल',
        Home:'घर',
        CurrentlyUnavailable:'इस समय अनुपलब्ध',
        OutOfStock:'स्टॉक ख़त्म',
        AllCategories:'सब वर्ग',
        WishList:'इच्छा-सूची',
        YourOrders:'तुम्हारे ऑर्डर',
        ManageProfile:'प्रोफ़ाइल प्रबंधित करें',
        PrivacyPolicy:'गोपनीयता नीति',
        Tearmsofuse:'उपयोग की शर्तें',
        FAQs:'पूछे जाने वाले प्रश्न',
        ChangeLanguage:'भाषा बदलें',
        LogOut:'लॉग आउट',
        EditYourProfile:'प्रोफ़ाइल संपादित करे',
        ShippingAddress:'शिपिंग पता',
        PaymentMethods:'भुगतान की विधि',
        OrderHistory:'आदेश इतिहास',
        DeliveryStatus:'वितरण की स्थिति',
        Favorite:'पसंदीदा',
        ChangePassword:'पासवर्ड बदलें',
        Help:'मदद',
        RateApp:'एप्प का मूल्यांकन',
        ShareApp:'ऐप शेयर करें',
        EditProfile:'प्रोफ़ाइल संपादित करें',
        SaveDetails:'विवरण सहेजें',
        MyOrder:'मेरा आदेश',
        PastOrder:'पिछला आदेश',
        Ongoning:'चल रहा है' ,
        OrderDetailes:'ऑर्डर का विवरण' ,
        MyOrders:'मेरे आदेश',
        OrderID:'आदेश कामतत्व',
        Address:'पता',
        PhoneNumber:'फ़ोन नंबर',
        Time:'समय' ,
        TrackingStatus:'ट्रैकिंग स्थिति',
        OrderPlaced:'आदेश रखा',
        OrderPrepared:'आदेश तैयार',
        OrderDispatch:'आदेश प्रेषण',
        outForDeliver:'डिलिवरी के लिए रवाना',
        OrderRecived:'आदेश प्राप्त',
        OrderDate:'आदेश की तारीख',
        ProductPage:'उत्पाद पृष्ठ',
        GoToBasket:'टोकरी में जाओ',
        Description:'विवरण',
        RelatedItems:'संबंधित चीजें',
        AllProducts:'सभी प्रोडक्ट',
        Notifications:'सूचनाएं',
        Name:'नाम',
        Note:'नोट: कृपया एक्सेस के लिए प्रतीक्षा करें अन्यथा आप +91 xxxx xxxx . पर कॉल कर सकते हैं',
        AllCategories:'सब वर्ग',
        BillDetailes:'बिल विवरण',
        total:'संपूर्ण',
        Quantity:'मात्रा',
        Language:'भाषा',
        camera:"कैमरा",
        gallery:"गेलरी",
        ChooseYourPrefferedLanguage:'अपना पसंदीदा भाषा चुने ',
        NoInternetConnection:'कोई इंटरनेट कनेक्शन नहीं',
        PleaseTryAgainLater:'कृपया बाद में पुन: प्रयास करें',
        AreYouSureYouWant:"क्या आप लॉग आउट करना चाहते हैं?",
        cancel:"रद्द करना",
        Logout:"लॉग आउट",
        signup:"साइन इन ",
        signin:"साइन अप ",
        Email:"ईमेल",
        password:"पासवर्ड",
        confirmpassword:"पासवर्ड की पुष्टि ",
        forgotpassword:"पासवर्ड भूल गए?",
        shopdetails:"दुकान विवरण",
        donthaveaccount:"अकाउंट नहीं है?",
        signUP:"साइन अप करें",
        selectyourfile:"अपनी फ़ाइल चुनें",
        shopname:"दुकान का नाम",
        nameofuser:"उपयोगकर्ता का नाम",
        addressofshop:"दुकान का पता",
        phonenumber:"फ़ोन नंबर",
        imageofshop:"दुकान की तस्वीर",
        adharcard:"आधार कार्ड",
        businesscard:"बिज़नेस कार्ड",
        salesorreference:"बिक्री/संदर्भ",
        referencecode:"संदर्भ व्यक्ति कोड",
        alreadyhaveaccount:"क्या आपके पास पहले से एक अकाउंट  मौजूद है?",
        signIn:"साइन इन करें",
        weigths:"वजन",
        selectweigth:"वजन चुनें",
        pleasecheckyouremail:"कृपया अपनी ईमेल देखें",
        confirmemail:"ईमेल की पुष्टि करें",
        orderhistory:"आदेश इतिहास",
        ongoingorder:"चालू आर्डर",
        pastorder:"पिछला आर्डर",
        pleaseentervaildEmail:"कृपया वैध ईमेल दर्ज़ करें",
        pleaseenterpassword:"कृपया पासवर्ड दर्ज करें",
        passworandconfirmpassword:"पासवर्ड और कन्फर्म पासवर्ड समान नहीं हैं",
        pleaseentershopname:"कृपया दुकान का नाम दर्ज करें",
        pleaseenterusername:"कृपया उपयोगकर्ता नाम दर्ज करें",
        pleaseenterphonenumber:"कृपया फोन नंबर दर्ज करें",
        pleaseentershopaddress:"कृपया दुकान का पता दर्ज करें",
        pleaseentervaildphonenumber:"कृपया एक वैध नंबर डालें",
        pleaseinsertshopimage:"कृपया दुकान छवियाँ सम्मिलित करें",
        pleaseinsertbuisnesscard:"कृपया बिजनेस कार्ड डालें",
        pleaselectweigthofproduct:"कृपया वजन चुनें",
        addtowishlist:"इच्छा सूची में जोड़ें",
        forgotPassword:"फॉरगोट पासवर्ड",
        pleaseenteremailtoconfirm:"पुष्टिकरण प्राप्त करने के लिए कृपया अपना ईमेल दर्ज करें और नया पासवर्ड सेट करें",
        addedtowishlist:"इच्छा सूची में जोड़ना",
        removedfromwishlist:"इच्छा सूची से हटाया गया",
        thisproductarenotunavailable:"ये उत्पाद वर्तमान में अनुपलब्ध हैं",
        Productid:"उत्पाद आयडी",
        clearall:"सभी साफ करें",
        status:"वितरण की स्थिति",
        pleaseenterEmail:"कृपया ईमेल दर्ज करें",

        invaildcredentails:"अमान्य क्रेडेंशियल",
        pleasecheckyouremailandpassword:"कृपया अपना ईमेल आईडी और पासवर्ड जांचें",
        okay:"ठीक है",
        weakpassword:"पासवर्ड कम से कम 6 अंक का होना चाहिए",
        emailalreadyexist:"यह ईमेल पहले से मौजूद है",
        congratulations:"बधाई हो",
        sucessfullregister:"आपने सफलतापूर्वक पंजीकरण कर लिया है",
        requestunderreview:"आपके अनुरोध की समीक्षा की जा रही है",
        wrongpassword:"पासवर्ड ईमेल से मेल नहीं खाता",
        wrongemail:"आपके द्वारा दर्ज किया गया ईमेल सही नहीं है",
        referencecodeerror:"संदर्भ व्यक्ति कोड मौजूद नहीं है",
        invaildemail:"ईमेल मान्य नहीं है",
        linksend:"लिंक आपको दिए गए ईमेल पर सफलतापूर्वक भेज दिया गया है",
        alert:"एलर्ट",
        update:"अपडेट",
        updatemsg:"परफेक्ट डिजिटल मार्ट अनुशंसा करता है कि आप इसे अपडेट करे नवीनतम संस्करण।",
        updatealert:"परफेक्ट डिजिटल मार्ट अपडेट करें?",
        nothanks:"जी नहीं, धन्यवाद",
        noproductavailable:'कोई प्रॉडक्ट उपलब्ध नहीं है',
        addressavailable:'आपका पता जहां प्रॉडक्ट वितरित किया जाएगा',
        saveaddress:'पता बचाओ',
        off:"छूट"
    }
}
export default library;